<a href="https://colab.research.google.com/github/erickgt00/Deep-Learning/blob/main/Simulacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#PASO 0. INSTALACION DE LIBRERIAS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
from keras.models import Sequential
from keras.layers import Dense

In [24]:
#PASO 1. LEER LA BASE DE DATOS
ERDB = pd.read_csv('EarlyRetirementPrediction (1).csv')
ERDB.head()

,Retire Before 65 Years Old,Gender,Desease,Education Level,Marital Status,Monthly Income,Employee/Employer,Dependants,Unemployment Rate,Stock Market,Credit Score,Government Bonds Return
0,1,1,1,3,0,18000,0,4,3.444876,24066.16667,699,7.715833
1,0,1,0,3,0,32000,0,1,5.023797,42063.16667,639,5.414833
2,0,1,1,4,0,20000,0,2,5.355220,30100.50000,610,7.962750
3,0,0,1,4,1,35000,1,1,3.843570,24066.16667,649,7.715833
4,0,0,1,3,0,27000,0,1,4.949226,19439.00000,638,8.024167

In [25]:
#DEFINIR CONJUNTO DE ENTRENAMIENTO Y CONJUNTO DE PRUEBA

train, test = train_test_split(ERDB, test_size=0.2)

In [26]:
print(test)

      Retire Before 65 Years Old  Gender  Desease  Education Level  \
1376                           1       0        0                5
1419                           1       1        0                5
517                            1       1        0                3
100                            0       1        0                5
762                            0       0        1                4
...                          ...     ...      ...              ...
209                            1       1        0                1
1133                           0       0        0                3
395                            1       1        0                3
725                            0       0        0                3
646                            0       1        1                5

      Marital Status  Monthly Income  Employee/Employer  Dependants  \
1376               1           23000                  0           3
1419               0           35000                  1           1
517                1           26000                  1           3
100                0           22000                  0           1
762                0           16000                  0           1
...              ...             ...                ...         ...
209                1           16000                  0           3
1133               0           16000                  0           3
395                0           21000                  0           4
725                1           40000                  1           3
646                0           23000                  0           1

      Unemployment Rate  Stock Market  Credit Score  Government Bonds Return
1376           5.220307   36600.00000           621                 7.110000
1419           4.757275   40418.00000           691                 6.365083
517            4.882267   41912.16667           716                 5.567417
100            3.763394   29309.33333           784                 7.521667
762            3.705375   30373.83333           625                 7.982500
...                 ...           ...           ...                      ...
209            4.906788   44426.00000           794                 5.095083
1133           3.843570   24066.16667           745                 7.715833
395            2.966903   16516.83333           631                 8.589167
725            3.469161   19520.66667           699                 8.896667
646            5.353961   31577.33333           756                 7.701083

[300 rows x 12 columns]

In [27]:
train_x=train[["Gender","Desease","Education Level","Marital Status",
           "Monthly Income","Employee/Employer","Dependants",
           "Unemployment Rate","Stock Market","Credit Score","Government Bonds Return"]]
train_y=train[["Retire Before 65 Years Old"]]
test_x=test[["Gender","Desease","Education Level","Marital Status",
           "Monthly Income","Employee/Employer","Dependants",
           "Unemployment Rate","Stock Market","Credit Score","Government Bonds Return"]]
test_y=test[["Retire Before 65 Years Old"]]

In [28]:
#DEFINE SEQUENTIAL MODEL
model = Sequential()
model.add(Dense(4, input_dim=11, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

In [29]:
model.compile(loss='mean_squared_error', optimizer='SGD', metrics=['accuracy'])

In [30]:
model.fit(train_x, train_y, epochs=150, batch_size=10)

Epoch 1/150
120/120 [==============================] - 1s 2ms/step - loss: 0.2647 - accuracy: 0.4500
Epoch 2/150
120/120 [==============================] - 0s 1ms/step - loss: 0.2573 - accuracy: 0.4817
Epoch 3/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2534 - accuracy: 0.4817
Epoch 4/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2512 - accuracy: 0.4817
Epoch 5/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2498 - accuracy: 0.4850
Epoch 6/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2489 - accuracy: 0.5000
Epoch 7/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2486 - accuracy: 0.5400
Epoch 8/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2484 - accuracy: 0.5400
Epoch 9/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2483 - accuracy: 0.5400
Epoch 10/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2483 - accuracy: 0.5400
Epoch 11/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 12/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 13/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 14/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 15/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 16/150
120/120 [==============================] - 0s 1ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 17/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 18/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 19/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 20/150
120/120 [==============================] - 0s 3ms/step - loss: 0.2482 - accuracy: 0.5400
Epoch 21/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 22/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 23/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 24/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 25/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 26/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 27/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 28/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 29/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 30/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 31/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 32/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 33/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 34/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 35/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 36/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 37/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 38/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 39/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 40/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 41/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 42/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 43/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 44/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 45/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 46/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 47/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 48/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 49/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 50/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 51/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 52/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 53/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 54/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 55/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 56/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 57/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 58/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 59/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 60/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 61/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 62/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 63/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 64/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 65/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 66/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 67/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 68/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 69/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 70/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 71/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 72/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 73/150
120/120 [==============================] - 0s 1ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 74/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 75/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 76/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 77/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 78/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 79/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 80/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 81/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 82/150
120/120 [==============================] - 0s 3ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 83/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 84/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 85/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 86/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 87/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 88/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 89/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 90/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 91/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 92/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 93/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 94/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 95/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 96/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 97/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 98/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 99/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 100/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 101/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 102/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 103/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 104/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 105/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 106/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 107/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 108/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 109/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 110/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 111/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 112/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 113/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 114/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 115/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 116/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 117/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 118/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 119/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 120/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 121/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 122/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 123/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 124/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 125/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 126/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 127/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 128/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 129/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 130/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 131/150
120/120 [==============================] - 0s 3ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 132/150
120/120 [==============================] - 0s 4ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 133/150
120/120 [==============================] - 1s 6ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 134/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 135/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 136/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 137/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 138/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 139/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 140/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 141/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 142/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 143/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 144/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 145/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 146/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 147/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 148/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400
Epoch 149/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2481 - accuracy: 0.5400
Epoch 150/150
120/120 [==============================] - 0s 2ms/step - loss: 0.2480 - accuracy: 0.5400

In [31]:
# evaluate the keras model
print("Evaluate on test data")
results = model.evaluate(test_x, test_y)
print("test loss, test acc:", results)

Evaluate on test data
10/10 [==============================] - 0s 3ms/step - loss: 0.2527 - accuracy: 0.4867
test loss, test acc: [0.2526601254940033, 0.4866666793823242]

In [32]:
# Generate predictions (probabilities -- the output of the last layer)
# on new data using `predict`
print("Generate predictions for 3 samples")
predictions = model.predict(test_x)
print("predictions shape:", predictions)

Generate predictions for 3 samples
10/10 [==============================] - 0s 10ms/step
predictions shape: [[0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.4124038 ]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.46957853]
 [0.4124038 ]
 [0.46957853]
 [0.4695785 ]
 [0.4124038 ]
 [0.4124038 ]
 [0.4695785 ]]

In [33]:
PredictionsDF=pd.DataFrame(predictions)
PredictionsDF.columns = ["Probabilities"]
PredictionsDF.head(20)

    Probabilities
0        0.469579
1        0.469579
2        0.469579
3        0.469579
4        0.469579
5        0.469579
6        0.469579
7        0.469579
8        0.469579
9        0.469579
10       0.469579
11       0.469579
12       0.469579
13       0.469579
14       0.469579
15       0.469579
16       0.469579
17       0.412404
18       0.412404
19       0.469579

In [34]:
PredictionsDF["Umbral"]=0
PredictionsDF.loc[PredictionsDF["Probabilities"] >0.5, "Umbral"] = 1
PredictionsDF.head(20)

    Probabilities  Umbral
0        0.469579       0
1        0.469579       0
2        0.469579       0
3        0.469579       0
4        0.469579       0
5        0.469579       0
6        0.469579       0
7        0.469579       0
8        0.469579       0
9        0.469579       0
10       0.469579       0
11       0.469579       0
12       0.469579       0
13       0.469579       0
14       0.469579       0
15       0.469579       0
16       0.469579       0
17       0.412404       0
18       0.412404       0
19       0.469579       0

In [35]:
test_y=pd.DataFrame(test_y)
test_y.head()

      Retire Before 65 Years Old
1376                           1
1419                           1
517                            1
100                            0
762                            0

In [36]:
PredictionsDF.reset_index(drop=True,inplace=True)
test_y.reset_index(drop=True,inplace=True)
print(test_y)

     Retire Before 65 Years Old
0                             1
1                             1
2                             1
3                             0
4                             0
..                          ...
295                           1
296                           0
297                           1
298                           0
299                           0

[300 rows x 1 columns]

In [37]:
data=pd.concat([PredictionsDF,test_y],axis=1)
data=pd.DataFrame(data)
data.head()

   Probabilities  Umbral  Retire Before 65 Years Old
0       0.469579       0                           1
1       0.469579       0                           1
2       0.469579       0                           1
3       0.469579       0                           0
4       0.469579       0                           0

In [38]:
data["PositivePositive"]=0
data["Sum1"]=data["Umbral"]+data["Retire Before 65 Years Old"]
data.loc[data["Sum1"] ==2, "PositivePositive"] = 1
data.head()

   Probabilities  Umbral  Retire Before 65 Years Old  PositivePositive  Sum1
0       0.469579       0                           1                 0     1
1       0.469579       0                           1                 0     1
2       0.469579       0                           1                 0     1
3       0.469579       0                           0                 0     0
4       0.469579       0                           0                 0     0

In [39]:
TPR=data["PositivePositive"].sum()/data["Retire Before 65 Years Old"].sum()
TPR

0.0

In [40]:
data["NegativeNegative"]=0
data.loc[data["Sum1"] ==0, "NegativeNegative"] = 1
data.head()

,Probabilities,Umbral,Retire Before 65 Years Old,PositivePositive,Sum1,NegativeNegative
0,0.469579,0,1,0,1,0
1,0.469579,0,1,0,1,0
2,0.469579,0,1,0,1,0
3,0.469579,0,0,0,0,1
4,0.469579,0,0,0,0,1

In [41]:
TNR=data["NegativeNegative"].sum()/(300-data["Retire Before 65 Years Old"].sum())
TNR

1.0

In [42]:
BA=(TPR+TNR)/2
BA

0.5

In [43]:
ACC=(data["NegativeNegative"].sum()+data["PositivePositive"].sum())/300
ACC

0.4866666666666667